#!/usr/bin/env python3
"""
Post-processes Yosys write_spice output to add VGND VNB VPB VPWR power pins
to every Sky130 standard cell instantiation.

Sky130 HD cell port order convention:
  All cells end with: ... VGND VNB VPB VPWR <output(s)>
  Yosys write_spice omits the power pins entirely.

We look up each cell's subcircuit definition in sky130_fd_sc_hd.spice
to get the exact port order, then insert GND/VDD in the right positions.
"""

import re
import sys

SPICE_LIB = "/Users/nizansari/.volare/sky130A/libs.ref/sky130_fd_sc_hd/spice/sky130_fd_sc_hd.spice"
INPUT      = "/Users/nizansari/Desktop/Projects/SAR ADC/sar_logic.spice"
OUTPUT     = "/Users/nizansari/Desktop/Projects/SAR ADC/sar_logic_fixed.spice"
VDD        = "VDD"
GND        = "GND"

# --- Step 1: parse port lists from PDK SPICE file ---
cell_ports = {}  # cell_name -> list of port names in order

with open(SPICE_LIB) as f:
    for line in f:
        line = line.strip()
        if line.lower().startswith(".subckt sky130_fd_sc_hd__"):
            parts = line.split()
            cell_name = parts[1]
            ports = parts[2:]
            cell_ports[cell_name] = ports

print(f"Loaded {len(cell_ports)} cell definitions from PDK.")

# --- Step 2: process the Yosys SPICE netlist ---
power_map = {
    "VGND": GND,
    "VNB":  GND,
    "VPB":  VDD,
    "VPWR": VDD,
}

out_lines = []
out_lines.append(f".include \"{SPICE_LIB}\"\n")

with open(INPUT) as f:
    for line in f:
        stripped = line.strip()

        # Skip the Yosys comment header (we'll add our own)
        if stripped.startswith("* SPICE netlist generated by Yosys"):
            out_lines.append("* SAR logic SPICE netlist — power pins added by fix_spice_ports.py\n")
            continue

        # Process subcircuit instantiation lines (start with X)
        if stripped.upper().startswith("X"):
            parts = stripped.split()
            inst_name = parts[0]
            cell_name = parts[-1]

            if cell_name in cell_ports:
                # Signal nodes from Yosys (everything except inst name and cell name)
                yosys_signals = parts[1:-1]
                pdk_ports = cell_ports[cell_name]

                # Count non-power ports in PDK definition
                signal_ports = [p for p in pdk_ports if p not in power_map]

                if len(yosys_signals) != len(signal_ports):
                    print(f"WARNING: {inst_name} ({cell_name}): "
                          f"expected {len(signal_ports)} signal ports, "
                          f"got {len(yosys_signals)} — skipping fix")
                    out_lines.append(line)
                    continue

                # Build full port list in PDK order
                sig_iter = iter(yosys_signals)
                full_ports = []
                for port in pdk_ports:
                    if port in power_map:
                        full_ports.append(power_map[port])
                    else:
                        full_ports.append(next(sig_iter))

                new_line = f"{inst_name} {' '.join(full_ports)} {cell_name}\n"
                out_lines.append(new_line)
            else:
                print(f"WARNING: cell '{cell_name}' not found in PDK — leaving line unchanged")
                out_lines.append(line)
        else:
            out_lines.append(line)

with open(OUTPUT, "w") as f:
    f.writelines(out_lines)

print(f"Written to {OUTPUT}")
