#!/usr/bin/env python3
"""
Post-processes Yosys write_spice output to:
1. Add power pins to every Sky130 standard cell instantiation
2. Resolve Yosys 0V net alias sources (Vxx A B DC 0) by merging nets
3. Wrap the netlist in a .subckt/.ends block
"""

import re

SPICE_LIB = "/Users/nizansari/.volare/sky130A/libs.ref/sky130_fd_sc_hd/spice/sky130_fd_sc_hd.spice"
INPUT      = "/Users/nizansari/Desktop/Projects/SAR ADC/sar_logic.spice"
OUTPUT     = "/Users/nizansari/Desktop/Projects/SAR ADC/sar_logic_fixed.spice"
VDD        = "VDD"
GND        = "GND"

POWER_PINS = {"VGND", "VNB", "VPB", "VPWR"}
POWER_MAP  = {"VGND": GND, "VNB": GND, "VPB": VDD, "VPWR": VDD}

SUBCKT_HEADER = (
    ".subckt sar_logic clkin rst start comp_in "
    "cdac_sw.9 cdac_sw.8 cdac_sw.7 cdac_sw.6 cdac_sw.5 "
    "cdac_sw.4 cdac_sw.3 cdac_sw.2 cdac_sw.1 cdac_sw.0 "
    "result.9 result.8 result.7 result.6 result.5 "
    "result.4 result.3 result.2 result.1 result.0 "
    "done VDD GND"
)

YOSYS_SIGNAL_ORDER_OVERRIDE = {
    "sky130_fd_sc_hd__dfrtp_1": ["CLK", "D", "Q", "RESET_B"],
    "sky130_fd_sc_hd__dfstp_2": ["CLK", "D", "Q", "SET_B"],
}

# --- Step 1: Parse SPICE library for port lists ---
spice_ports = {}
with open(SPICE_LIB) as f:
    for line in f:
        s = line.strip()
        if s.lower().startswith(".subckt sky130_fd_sc_hd__"):
            parts = s.split()
            spice_ports[parts[1]] = parts[2:]

print(f"Loaded {len(spice_ports)} cell port lists from SPICE library.")

# --- Step 2: Read input netlist ---
with open(INPUT) as f:
    raw_lines = f.readlines()

# --- Step 3: Build net alias map from 0V sources ---
# Vxx A B DC 0  means net A and net B are the same
# We build a union-find style map: alias[B] = A (replace B with A everywhere)
alias = {}

def resolve(net):
    """Follow alias chain to canonical net name."""
    while net in alias:
        net = alias[net]
    return net

for line in raw_lines:
    s = line.strip()
    # Match: Vname net1 net2 DC 0
    m = re.match(r'^V\S+\s+(\S+)\s+(\S+)\s+DC\s+0\s*$', s, re.IGNORECASE)
    if m:
        net_a, net_b = m.group(1), m.group(2)
        # Resolve existing aliases first
        canon_a = resolve(net_a)
        canon_b = resolve(net_b)
        if canon_a != canon_b:
            # Map the numeric/less-meaningful net to the named one
            # Prefer keeping named nets (non-numeric) as canonical
            if canon_b.isdigit() or (not canon_a.isdigit() and canon_b.isdigit()):
                alias[canon_b] = canon_a
            else:
                alias[canon_a] = canon_b

print(f"Built {len(alias)} net aliases from 0V sources.")

def sub_net(net):
    return resolve(net)

# --- Step 4: Process netlist ---
out_lines = []
out_lines.append(f".include \"{SPICE_LIB}\"\n")
out_lines.append("* SAR logic SPICE netlist — fixed by fix_spice_ports.py\n")
out_lines.append(f"{SUBCKT_HEADER}\n\n")

warnings = 0
skipped_vsources = 0

for line in raw_lines:
    stripped = line.strip()

    if stripped.startswith("* SPICE netlist generated by Yosys"):
        continue

    # Skip 0V alias sources — we've resolved them
    m = re.match(r'^V\S+\s+\S+\s+\S+\s+DC\s+0\s*$', stripped, re.IGNORECASE)
    if m:
        skipped_vsources += 1
        continue

    if stripped.upper().startswith("X"):
        parts = stripped.split()
        inst_name = parts[0]
        cell_name = parts[-1]

        if cell_name not in spice_ports:
            print(f"WARNING: '{cell_name}' not in SPICE library — leaving unchanged")
            out_lines.append(line)
            warnings += 1
            continue

        yosys_signals = [sub_net(p) for p in parts[1:-1]]
        spice_port_list = spice_ports[cell_name]
        spice_signal_ports = [p for p in spice_port_list if p not in POWER_PINS]
        yosys_order = YOSYS_SIGNAL_ORDER_OVERRIDE.get(cell_name, spice_signal_ports)

        if len(yosys_signals) != len(yosys_order):
            print(f"WARNING: {inst_name} ({cell_name}): "
                  f"expected {len(yosys_order)} signals, got {len(yosys_signals)} — leaving unchanged")
            out_lines.append(line)
            warnings += 1
            continue

        pin_to_net = dict(zip(yosys_order, yosys_signals))

        full_ports = []
        for port in spice_port_list:
            if port in POWER_MAP:
                full_ports.append(POWER_MAP[port])
            elif port in pin_to_net:
                full_ports.append(pin_to_net[port])
            else:
                print(f"WARNING: {inst_name} ({cell_name}): port '{port}' not in mapping")
                full_ports.append("UNKNOWN")
                warnings += 1

        new_line = f"{inst_name} {' '.join(full_ports)} {cell_name}\n"
        out_lines.append(new_line)
    else:
        # For non-X lines, substitute net aliases in the line
        # (handles any remaining V sources with non-zero values etc.)
        out_lines.append(line)

out_lines.append("\n.ends sar_logic\n")

with open(OUTPUT, "w") as f:
    f.writelines(out_lines)

print(f"Skipped {skipped_vsources} 0V alias sources.")
print(f"Done. {warnings} warnings. Written to {OUTPUT}")