/* Generated by Yosys 0.66 (git sha1 7f8fdfd8d7bc08c749a2a969388d3425d4f369d5, clang++ 17.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "sar_logic.v:1.1-53.10" *)
module sar_logic(clk, rst, start, comp_in, cdac_sw, result, done);
  (* src = "sar_logic.v:2.24-2.27" *)
  input clk;
  wire clk;
  (* src = "sar_logic.v:3.24-3.27" *)
  input rst;
  wire rst;
  (* src = "sar_logic.v:4.24-4.29" *)
  input start;
  wire start;
  (* src = "sar_logic.v:5.24-5.31" *)
  input comp_in;
  wire comp_in;
  (* src = "sar_logic.v:6.24-6.31" *)
  output [9:0] cdac_sw;
  reg [9:0] cdac_sw;
  (* src = "sar_logic.v:7.24-7.30" *)
  output [9:0] result;
  reg [9:0] result;
  (* src = "sar_logic.v:8.24-8.28" *)
  output done;
  reg done;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire [9:0] _000_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire [9:0] _001_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _002_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire [3:0] _003_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _081_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _082_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _083_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _084_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _085_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _086_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _087_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _088_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _089_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _090_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _091_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _092_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _093_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _094_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _095_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _096_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _097_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _098_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _099_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _100_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _101_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _102_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _103_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _104_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _105_;
  (* src = "sar_logic.v:14.5-51.8" *)
  wire _106_;
  wire _107_;
  wire _108_;
  (* src = "sar_logic.v:12.15-12.21" *)
  wire _109_;
  (* src = "sar_logic.v:11.15-11.22" *)
  wire _110_;
  (* src = "sar_logic.v:11.15-11.22" *)
  wire _111_;
  (* src = "sar_logic.v:11.15-11.22" *)
  wire _112_;
  (* src = "sar_logic.v:11.15-11.22" *)
  wire _113_;
  (* src = "sar_logic.v:6.24-6.31" *)
  wire _114_;
  (* src = "sar_logic.v:6.24-6.31" *)
  wire _115_;
  (* src = "sar_logic.v:6.24-6.31" *)
  wire _116_;
  (* src = "sar_logic.v:6.24-6.31" *)
  wire _117_;
  (* src = "sar_logic.v:6.24-6.31" *)
  wire _118_;
  (* src = "sar_logic.v:6.24-6.31" *)
  wire _119_;
  (* src = "sar_logic.v:6.24-6.31" *)
  wire _120_;
  (* src = "sar_logic.v:6.24-6.31" *)
  wire _121_;
  (* src = "sar_logic.v:6.24-6.31" *)
  wire _122_;
  (* src = "sar_logic.v:6.24-6.31" *)
  wire _123_;
  (* src = "sar_logic.v:5.24-5.31" *)
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  (* src = "sar_logic.v:7.24-7.30" *)
  wire _181_;
  (* src = "sar_logic.v:7.24-7.30" *)
  wire _182_;
  (* src = "sar_logic.v:7.24-7.30" *)
  wire _183_;
  (* src = "sar_logic.v:7.24-7.30" *)
  wire _184_;
  (* src = "sar_logic.v:7.24-7.30" *)
  wire _185_;
  (* src = "sar_logic.v:7.24-7.30" *)
  wire _186_;
  (* src = "sar_logic.v:7.24-7.30" *)
  wire _187_;
  (* src = "sar_logic.v:7.24-7.30" *)
  wire _188_;
  (* src = "sar_logic.v:7.24-7.30" *)
  wire _189_;
  (* src = "sar_logic.v:7.24-7.30" *)
  wire _190_;
  (* src = "sar_logic.v:4.24-4.29" *)
  wire _191_;
  (* src = "sar_logic.v:12.15-12.21" *)
  reg active;
  (* src = "sar_logic.v:11.15-11.22" *)
  reg [3:0] bit_idx;
  sky130_fd_sc_hd__clkinv_1 _192_ (
    .A(_112_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__clkinv_1 _193_ (
    .A(_113_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__clkinv_1 _194_ (
    .A(_114_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _195_ (
    .A(_191_),
    .SLEEP(_109_),
    .X(_149_)
  );
  sky130_fd_sc_hd__clkinv_1 _196_ (
    .A(_149_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nor2_1 _197_ (
    .A(_110_),
    .B(_111_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nor3_1 _198_ (
    .A(_110_),
    .B(_111_),
    .C(_112_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__or3_1 _199_ (
    .A(_110_),
    .B(_111_),
    .C(_112_),
    .X(_152_)
  );
  sky130_fd_sc_hd__o21ai_0 _200_ (
    .A1(_110_),
    .A2(_111_),
    .B1(_112_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__a21oi_1 _201_ (
    .A1(_152_),
    .A2(_153_),
    .B1(_149_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _202_ (
    .A(_111_),
    .SLEEP(_110_),
    .X(_154_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _203_ (
    .A(_110_),
    .SLEEP(_111_),
    .X(_155_)
  );
  sky130_fd_sc_hd__nor3_1 _204_ (
    .A(_149_),
    .B(_154_),
    .C(_155_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand2_1 _205_ (
    .A(_110_),
    .B(_106_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nor2_1 _206_ (
    .A(_113_),
    .B(_152_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nand2_1 _207_ (
    .A(_147_),
    .B(_151_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__nand2_1 _208_ (
    .A(_106_),
    .B(_157_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _209_ (
    .A(_112_),
    .SLEEP(_113_),
    .X(_159_)
  );
  sky130_fd_sc_hd__nand3_1 _210_ (
    .A(_110_),
    .B(_111_),
    .C(_159_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__nand4_1 _211_ (
    .A(_110_),
    .B(_111_),
    .C(_124_),
    .D(_159_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__nand2_1 _212_ (
    .A(_113_),
    .B(_151_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nand2_1 _213_ (
    .A(_121_),
    .B(_160_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__a31oi_1 _214_ (
    .A1(_161_),
    .A2(_162_),
    .A3(_163_),
    .B1(_158_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nand2_1 _215_ (
    .A(_154_),
    .B(_159_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nand4_1 _216_ (
    .A(_112_),
    .B(_147_),
    .C(_124_),
    .D(_154_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nand2_1 _217_ (
    .A(_120_),
    .B(_164_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__a31oi_1 _218_ (
    .A1(_160_),
    .A2(_165_),
    .A3(_166_),
    .B1(_158_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nand2_1 _219_ (
    .A(_155_),
    .B(_159_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__nand4_1 _220_ (
    .A(_112_),
    .B(_147_),
    .C(_124_),
    .D(_155_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nand2_1 _221_ (
    .A(_119_),
    .B(_167_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__a31oi_1 _222_ (
    .A1(_164_),
    .A2(_168_),
    .A3(_169_),
    .B1(_158_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nand2_1 _223_ (
    .A(_150_),
    .B(_159_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nand2_1 _224_ (
    .A(_118_),
    .B(_170_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nand3_1 _225_ (
    .A(_124_),
    .B(_150_),
    .C(_159_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__a31oi_1 _226_ (
    .A1(_167_),
    .A2(_171_),
    .A3(_172_),
    .B1(_158_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__and4_1 _227_ (
    .A(_110_),
    .B(_111_),
    .C(_146_),
    .D(_147_),
    .X(_173_)
  );
  sky130_fd_sc_hd__nand4_1 _228_ (
    .A(_110_),
    .B(_111_),
    .C(_146_),
    .D(_147_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nand2_1 _229_ (
    .A(_117_),
    .B(_174_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__and4_1 _230_ (
    .A(_147_),
    .B(_124_),
    .C(_152_),
    .D(_153_),
    .X(_176_)
  );
  sky130_fd_sc_hd__nand2_1 _231_ (
    .A(_124_),
    .B(_173_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__a31oi_1 _232_ (
    .A1(_170_),
    .A2(_175_),
    .A3(_177_),
    .B1(_158_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nand2_1 _233_ (
    .A(_154_),
    .B(_176_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__nand3_1 _234_ (
    .A(_146_),
    .B(_147_),
    .C(_154_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__a21oi_1 _235_ (
    .A1(_116_),
    .A2(_179_),
    .B1(_173_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__a21oi_1 _236_ (
    .A1(_178_),
    .A2(_180_),
    .B1(_158_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand2_1 _237_ (
    .A(_155_),
    .B(_176_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nand3_1 _238_ (
    .A(_146_),
    .B(_147_),
    .C(_155_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nand2_1 _239_ (
    .A(_115_),
    .B(_126_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__a31oi_1 _240_ (
    .A1(_179_),
    .A2(_125_),
    .A3(_127_),
    .B1(_158_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__a21oi_1 _241_ (
    .A1(_148_),
    .A2(_126_),
    .B1(_158_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nand3_1 _242_ (
    .A(_113_),
    .B(_124_),
    .C(_151_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nand2_1 _243_ (
    .A(_189_),
    .B(_162_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__a21oi_1 _244_ (
    .A1(_128_),
    .A2(_129_),
    .B1(_149_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nand2_1 _245_ (
    .A(_188_),
    .B(_160_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__a21oi_1 _246_ (
    .A1(_161_),
    .A2(_130_),
    .B1(_149_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nand2_1 _247_ (
    .A(_187_),
    .B(_164_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__a21oi_1 _248_ (
    .A1(_165_),
    .A2(_131_),
    .B1(_149_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nand2_1 _249_ (
    .A(_186_),
    .B(_167_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__a21oi_1 _250_ (
    .A1(_168_),
    .A2(_132_),
    .B1(_149_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nand2_1 _251_ (
    .A(_185_),
    .B(_170_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__a21oi_1 _252_ (
    .A1(_172_),
    .A2(_133_),
    .B1(_149_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand2_1 _253_ (
    .A(_184_),
    .B(_174_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__a21oi_1 _254_ (
    .A1(_177_),
    .A2(_134_),
    .B1(_149_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nand2_1 _255_ (
    .A(_183_),
    .B(_179_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__a21oi_1 _256_ (
    .A1(_178_),
    .A2(_135_),
    .B1(_149_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nand2_1 _257_ (
    .A(_182_),
    .B(_126_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__a21oi_1 _258_ (
    .A1(_125_),
    .A2(_136_),
    .B1(_149_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nand3_1 _259_ (
    .A(_181_),
    .B(_106_),
    .C(_157_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nand3_1 _260_ (
    .A(_124_),
    .B(_106_),
    .C(_156_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nand2_1 _261_ (
    .A(_137_),
    .B(_138_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__and3_1 _262_ (
    .A(_146_),
    .B(_113_),
    .C(_155_),
    .X(_139_)
  );
  sky130_fd_sc_hd__nand3_1 _263_ (
    .A(_146_),
    .B(_113_),
    .C(_155_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nor2_1 _264_ (
    .A(_124_),
    .B(_140_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__o21ai_0 _265_ (
    .A1(_190_),
    .A2(_139_),
    .B1(_106_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nor2_1 _266_ (
    .A(_141_),
    .B(_142_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__a311oi_1 _267_ (
    .A1(_146_),
    .A2(_113_),
    .A3(_154_),
    .B1(_139_),
    .C1(_123_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__o31ai_1 _268_ (
    .A1(_156_),
    .A2(_141_),
    .A3(_143_),
    .B1(_106_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _269_ (
    .A(_109_),
    .SLEEP(_191_),
    .X(_107_)
  );
  sky130_fd_sc_hd__nand2_1 _270_ (
    .A(_109_),
    .B(_157_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__and2_0 _271_ (
    .A(_107_),
    .B(_144_),
    .X(_108_)
  );
  sky130_fd_sc_hd__a21o_1 _272_ (
    .A1(_113_),
    .A2(_152_),
    .B1(_158_),
    .X(_105_)
  );
  sky130_fd_sc_hd__nand2_1 _273_ (
    .A(_106_),
    .B(_144_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nand2_1 _274_ (
    .A(_122_),
    .B(_162_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__a31oi_1 _275_ (
    .A1(_128_),
    .A2(_140_),
    .A3(_145_),
    .B1(_158_),
    .Y(_089_)
  );
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) bit_idx[0] <= 1'h1;
    else if (_002_) bit_idx[0] <= _003_[0];
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) bit_idx[1] <= 1'h0;
    else if (_002_) bit_idx[1] <= _003_[1];
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) bit_idx[2] <= 1'h0;
    else if (_002_) bit_idx[2] <= _003_[2];
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) bit_idx[3] <= 1'h1;
    else if (_002_) bit_idx[3] <= _003_[3];
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) cdac_sw[0] <= 1'h0;
    else if (_005_) cdac_sw[0] <= _000_[0];
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) cdac_sw[1] <= 1'h0;
    else if (_005_) cdac_sw[1] <= _000_[1];
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) cdac_sw[2] <= 1'h0;
    else if (_005_) cdac_sw[2] <= _000_[2];
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) cdac_sw[3] <= 1'h0;
    else if (_005_) cdac_sw[3] <= _000_[3];
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) cdac_sw[4] <= 1'h0;
    else if (_005_) cdac_sw[4] <= _000_[4];
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) cdac_sw[5] <= 1'h0;
    else if (_005_) cdac_sw[5] <= _000_[5];
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) cdac_sw[6] <= 1'h0;
    else if (_005_) cdac_sw[6] <= _000_[6];
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) cdac_sw[7] <= 1'h0;
    else if (_005_) cdac_sw[7] <= _000_[7];
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) cdac_sw[8] <= 1'h0;
    else if (_005_) cdac_sw[8] <= _000_[8];
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) cdac_sw[9] <= 1'h0;
    else if (_005_) cdac_sw[9] <= _000_[9];
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) result[0] <= 1'h0;
    else if (_005_) result[0] <= _001_[0];
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) result[1] <= 1'h0;
    else if (_005_) result[1] <= _001_[1];
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) result[2] <= 1'h0;
    else if (_005_) result[2] <= _001_[2];
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) result[3] <= 1'h0;
    else if (_005_) result[3] <= _001_[3];
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) result[4] <= 1'h0;
    else if (_005_) result[4] <= _001_[4];
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) result[5] <= 1'h0;
    else if (_005_) result[5] <= _001_[5];
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) result[6] <= 1'h0;
    else if (_005_) result[6] <= _001_[6];
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) result[7] <= 1'h0;
    else if (_005_) result[7] <= _001_[7];
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) result[8] <= 1'h0;
    else if (_005_) result[8] <= _001_[8];
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) result[9] <= 1'h0;
    else if (_005_) result[9] <= _001_[9];
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) done <= 1'h0;
    else if (_006_) done <= _004_;
  (* src = "sar_logic.v:14.5-51.8" *)
  always @(posedge clk, posedge rst)
    if (rst) active <= 1'h0;
    else active <= _002_;
  assign _110_ = bit_idx[0];
  assign _111_ = bit_idx[1];
  assign _112_ = bit_idx[2];
  assign _109_ = active;
  assign _191_ = start;
  assign _004_ = _106_;
  assign _003_[2] = _104_;
  assign _003_[1] = _103_;
  assign _003_[0] = _102_;
  assign _113_ = bit_idx[3];
  assign _124_ = comp_in;
  assign _121_ = cdac_sw[7];
  assign _000_[7] = _088_;
  assign _120_ = cdac_sw[6];
  assign _000_[6] = _087_;
  assign _119_ = cdac_sw[5];
  assign _000_[5] = _086_;
  assign _118_ = cdac_sw[4];
  assign _000_[4] = _085_;
  assign _117_ = cdac_sw[3];
  assign _000_[3] = _084_;
  assign _116_ = cdac_sw[2];
  assign _000_[2] = _083_;
  assign _115_ = cdac_sw[1];
  assign _000_[1] = _082_;
  assign _114_ = cdac_sw[0];
  assign _000_[0] = _081_;
  assign _189_ = result[8];
  assign _001_[8] = _099_;
  assign _188_ = result[7];
  assign _001_[7] = _098_;
  assign _187_ = result[6];
  assign _001_[6] = _097_;
  assign _186_ = result[5];
  assign _001_[5] = _096_;
  assign _185_ = result[4];
  assign _001_[4] = _095_;
  assign _184_ = result[3];
  assign _001_[3] = _094_;
  assign _183_ = result[2];
  assign _001_[2] = _093_;
  assign _182_ = result[1];
  assign _001_[1] = _092_;
  assign _181_ = result[0];
  assign _001_[0] = _091_;
  assign _190_ = result[9];
  assign _001_[9] = _100_;
  assign _123_ = cdac_sw[9];
  assign _000_[9] = _090_;
  assign _005_ = _107_;
  assign _006_ = _108_;
  assign _003_[3] = _105_;
  assign _002_ = _101_;
  assign _122_ = cdac_sw[8];
  assign _000_[8] = _089_;
endmodule
