/* Generated by Yosys 0.66 (git sha1 7f8fdfd8d7bc08c749a2a969388d3425d4f369d5, clang++ 17.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "sar_logic_renamed.v:1.1-53.10" *)
module sar_logic(clkin, rst, start, comp_in, cdac_sw, result, done);
  (* src = "sar_logic_renamed.v:2.24-2.29" *)
  input clkin;
  wire clkin;
  (* src = "sar_logic_renamed.v:3.24-3.27" *)
  input rst;
  wire rst;
  (* src = "sar_logic_renamed.v:4.24-4.29" *)
  input start;
  wire start;
  (* src = "sar_logic_renamed.v:5.24-5.31" *)
  input comp_in;
  wire comp_in;
  (* src = "sar_logic_renamed.v:6.24-6.31" *)
  output [9:0] cdac_sw;
  wire [9:0] cdac_sw;
  (* src = "sar_logic_renamed.v:7.24-7.30" *)
  output [9:0] result;
  wire [9:0] result;
  (* src = "sar_logic_renamed.v:8.24-8.28" *)
  output done;
  wire done;
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  wire [9:0] _000_;
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  wire [9:0] _001_;
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  wire _002_;
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  wire [3:0] _003_;
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  wire _081_;
  (* src = "sar_logic_renamed.v:12.15-12.21" *)
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  (* src = "sar_logic_renamed.v:11.15-11.22" *)
  wire _134_;
  (* src = "sar_logic_renamed.v:11.15-11.22" *)
  wire _135_;
  (* src = "sar_logic_renamed.v:11.15-11.22" *)
  wire _136_;
  (* src = "sar_logic_renamed.v:11.15-11.22" *)
  wire _137_;
  (* src = "sar_logic_renamed.v:6.24-6.31" *)
  wire _138_;
  (* src = "sar_logic_renamed.v:6.24-6.31" *)
  wire _139_;
  (* src = "sar_logic_renamed.v:6.24-6.31" *)
  wire _140_;
  (* src = "sar_logic_renamed.v:6.24-6.31" *)
  wire _141_;
  (* src = "sar_logic_renamed.v:6.24-6.31" *)
  wire _142_;
  (* src = "sar_logic_renamed.v:6.24-6.31" *)
  wire _143_;
  (* src = "sar_logic_renamed.v:6.24-6.31" *)
  wire _144_;
  (* src = "sar_logic_renamed.v:6.24-6.31" *)
  wire _145_;
  (* src = "sar_logic_renamed.v:6.24-6.31" *)
  wire _146_;
  (* src = "sar_logic_renamed.v:6.24-6.31" *)
  wire _147_;
  (* src = "sar_logic_renamed.v:5.24-5.31" *)
  wire _148_;
  (* src = "sar_logic_renamed.v:8.24-8.28" *)
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  (* src = "sar_logic_renamed.v:7.24-7.30" *)
  wire _215_;
  (* src = "sar_logic_renamed.v:7.24-7.30" *)
  wire _216_;
  (* src = "sar_logic_renamed.v:7.24-7.30" *)
  wire _217_;
  (* src = "sar_logic_renamed.v:7.24-7.30" *)
  wire _218_;
  (* src = "sar_logic_renamed.v:7.24-7.30" *)
  wire _219_;
  (* src = "sar_logic_renamed.v:7.24-7.30" *)
  wire _220_;
  (* src = "sar_logic_renamed.v:7.24-7.30" *)
  wire _221_;
  (* src = "sar_logic_renamed.v:7.24-7.30" *)
  wire _222_;
  (* src = "sar_logic_renamed.v:7.24-7.30" *)
  wire _223_;
  (* src = "sar_logic_renamed.v:7.24-7.30" *)
  wire _224_;
  (* src = "sar_logic_renamed.v:3.24-3.27" *)
  wire _225_;
  (* src = "sar_logic_renamed.v:4.24-4.29" *)
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  (* src = "sar_logic_renamed.v:12.15-12.21" *)
  wire active;
  (* src = "sar_logic_renamed.v:11.15-11.22" *)
  wire [3:0] bit_idx;
  sky130_fd_sc_hd__clkinv_1 _278_ (
    .A(_138_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__clkinv_1 _279_ (
    .A(_137_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__clkinv_1 _280_ (
    .A(_136_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__clkinv_1 _281_ (
    .A(_082_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__clkinv_1 _282_ (
    .A(_225_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nor3_1 _283_ (
    .A(_134_),
    .B(_135_),
    .C(_136_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__or3_1 _284_ (
    .A(_134_),
    .B(_135_),
    .C(_136_),
    .X(_203_)
  );
  sky130_fd_sc_hd__or4_1 _285_ (
    .A(_137_),
    .B(_134_),
    .C(_135_),
    .D(_136_),
    .X(_204_)
  );
  sky130_fd_sc_hd__a21oi_1 _286_ (
    .A1(_199_),
    .A2(_202_),
    .B1(_201_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__nand2_1 _287_ (
    .A(_082_),
    .B(_204_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__nand2b_1 _288_ (
    .A_N(_135_),
    .B(_134_),
    .Y(_207_)
  );
  sky130_fd_sc_hd__or4_1 _289_ (
    .A(_137_),
    .B(_136_),
    .C(_201_),
    .D(_207_),
    .X(_208_)
  );
  sky130_fd_sc_hd__nor2_1 _290_ (
    .A(_082_),
    .B(_226_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _291_ (
    .A(_226_),
    .SLEEP(_082_),
    .X(_210_)
  );
  sky130_fd_sc_hd__nand2_1 _292_ (
    .A(_201_),
    .B(_226_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__nand2_1 _293_ (
    .A(_082_),
    .B(_202_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__nor2_1 _294_ (
    .A(_201_),
    .B(_204_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__nor2_1 _295_ (
    .A(_210_),
    .B(_213_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__a211oi_1 _296_ (
    .A1(_198_),
    .A2(_208_),
    .B1(_210_),
    .C1(_213_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__o21ai_0 _297_ (
    .A1(_134_),
    .A2(_135_),
    .B1(_136_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nand4_1 _298_ (
    .A(_199_),
    .B(_148_),
    .C(_203_),
    .D(_150_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__nand2b_1 _299_ (
    .A_N(_134_),
    .B(_135_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nor2_1 _300_ (
    .A(_136_),
    .B(_152_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _301_ (
    .A1_N(_199_),
    .A2_N(_153_),
    .B1(_151_),
    .B2(_207_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__a32o_1 _302_ (
    .A1(_139_),
    .A2(_208_),
    .A3(_214_),
    .B1(_154_),
    .B2(_205_),
    .X(_132_)
  );
  sky130_fd_sc_hd__nand2_1 _303_ (
    .A(_134_),
    .B(_135_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__nor4bb_1 _304_ (
    .A(_137_),
    .B(_136_),
    .C_N(_135_),
    .D_N(_134_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__o2111ai_1 _305_ (
    .A1(_134_),
    .A2(_148_),
    .B1(_135_),
    .C1(_199_),
    .D1(_200_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__nor2_1 _306_ (
    .A(_206_),
    .B(_157_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__a31oi_1 _307_ (
    .A1(_199_),
    .A2(_082_),
    .A3(_153_),
    .B1(_210_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _308_ (
    .A(_204_),
    .SLEEP(_209_),
    .X(_160_)
  );
  sky130_fd_sc_hd__a31o_1 _309_ (
    .A1(_140_),
    .A2(_159_),
    .A3(_160_),
    .B1(_158_),
    .X(_131_)
  );
  sky130_fd_sc_hd__nor2_1 _310_ (
    .A(_149_),
    .B(_213_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__nor2_1 _311_ (
    .A(_210_),
    .B(_161_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nor4b_1 _312_ (
    .A(_137_),
    .B(_134_),
    .C(_135_),
    .D_N(_136_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__a21oi_1 _313_ (
    .A1(_148_),
    .A2(_156_),
    .B1(_162_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__a21oi_1 _314_ (
    .A1(_082_),
    .A2(_156_),
    .B1(_210_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nand3_1 _315_ (
    .A(_141_),
    .B(_160_),
    .C(_164_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__o21ai_0 _316_ (
    .A1(_206_),
    .A2(_163_),
    .B1(_165_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nor4bb_1 _317_ (
    .A(_135_),
    .B(_136_),
    .C_N(_137_),
    .D_N(_134_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__nand2_1 _318_ (
    .A(_224_),
    .B(_209_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _319_ (
    .A(_166_),
    .SLEEP(_148_),
    .X(_168_)
  );
  sky130_fd_sc_hd__o21ai_0 _320_ (
    .A1(_224_),
    .A2(_166_),
    .B1(_082_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__o21ai_0 _321_ (
    .A1(_168_),
    .A2(_169_),
    .B1(_167_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nand3b_1 _322_ (
    .A_N(_137_),
    .B(_136_),
    .C(_082_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nor2_1 _323_ (
    .A(_207_),
    .B(_170_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__a31oi_1 _324_ (
    .A1(_082_),
    .A2(_148_),
    .A3(_162_),
    .B1(_171_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__a21oi_1 _325_ (
    .A1(_082_),
    .A2(_162_),
    .B1(_210_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__nand3_1 _326_ (
    .A(_142_),
    .B(_160_),
    .C(_173_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nand2_1 _327_ (
    .A(_172_),
    .B(_174_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _328_ (
    .A1_N(_168_),
    .A2_N(_206_),
    .B1(_201_),
    .B2(_147_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__a211oi_1 _329_ (
    .A1(_137_),
    .A2(_153_),
    .B1(_166_),
    .C1(_147_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__o21ai_0 _330_ (
    .A1(_175_),
    .A2(_176_),
    .B1(_211_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nor2_1 _331_ (
    .A(_210_),
    .B(_171_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__and3_1 _332_ (
    .A(_148_),
    .B(_204_),
    .C(_171_),
    .X(_178_)
  );
  sky130_fd_sc_hd__nor2_1 _333_ (
    .A(_152_),
    .B(_170_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__a311o_1 _334_ (
    .A1(_143_),
    .A2(_160_),
    .A3(_177_),
    .B1(_178_),
    .C1(_179_),
    .X(_125_)
  );
  sky130_fd_sc_hd__nor2_1 _335_ (
    .A(_210_),
    .B(_179_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__nand2_1 _336_ (
    .A(_144_),
    .B(_160_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__nor2_1 _337_ (
    .A(_155_),
    .B(_170_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__a21oi_1 _338_ (
    .A1(_148_),
    .A2(_179_),
    .B1(_182_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__o31ai_1 _339_ (
    .A1(_210_),
    .A2(_179_),
    .A3(_181_),
    .B1(_183_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nor2_1 _340_ (
    .A(_210_),
    .B(_182_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__and2_0 _341_ (
    .A(_148_),
    .B(_182_),
    .X(_185_)
  );
  sky130_fd_sc_hd__nor2_1 _342_ (
    .A(_199_),
    .B(_212_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__a311o_1 _343_ (
    .A1(_145_),
    .A2(_160_),
    .A3(_184_),
    .B1(_185_),
    .C1(_186_),
    .X(_123_)
  );
  sky130_fd_sc_hd__nand2_1 _344_ (
    .A(_206_),
    .B(_211_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nand2_1 _345_ (
    .A(_137_),
    .B(_212_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__nand2_1 _346_ (
    .A(_211_),
    .B(_187_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nand2_1 _347_ (
    .A(_137_),
    .B(_148_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__a31oi_1 _348_ (
    .A1(_137_),
    .A2(_148_),
    .A3(_202_),
    .B1(_166_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__nand3_1 _349_ (
    .A(_146_),
    .B(_211_),
    .C(_212_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__o21ai_0 _350_ (
    .A1(_206_),
    .A2(_189_),
    .B1(_190_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__a22o_1 _351_ (
    .A1(_148_),
    .A2(_213_),
    .B1(_214_),
    .B2(_215_),
    .X(_120_)
  );
  sky130_fd_sc_hd__nand3_1 _352_ (
    .A(_216_),
    .B(_208_),
    .C(_211_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__o31ai_1 _353_ (
    .A1(_201_),
    .A2(_207_),
    .A3(_151_),
    .B1(_191_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nor3_1 _354_ (
    .A(_201_),
    .B(_151_),
    .C(_152_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__a21o_1 _355_ (
    .A1(_217_),
    .A2(_159_),
    .B1(_192_),
    .X(_118_)
  );
  sky130_fd_sc_hd__a32o_1 _356_ (
    .A1(_082_),
    .A2(_148_),
    .A3(_156_),
    .B1(_164_),
    .B2(_218_),
    .X(_117_)
  );
  sky130_fd_sc_hd__a32o_1 _357_ (
    .A1(_082_),
    .A2(_148_),
    .A3(_162_),
    .B1(_173_),
    .B2(_219_),
    .X(_116_)
  );
  sky130_fd_sc_hd__a21o_1 _358_ (
    .A1(_220_),
    .A2(_177_),
    .B1(_178_),
    .X(_115_)
  );
  sky130_fd_sc_hd__a22o_1 _359_ (
    .A1(_148_),
    .A2(_179_),
    .B1(_180_),
    .B2(_221_),
    .X(_114_)
  );
  sky130_fd_sc_hd__a21o_1 _360_ (
    .A1(_222_),
    .A2(_184_),
    .B1(_185_),
    .X(_113_)
  );
  sky130_fd_sc_hd__nand2_1 _361_ (
    .A(_223_),
    .B(_211_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__o22ai_1 _362_ (
    .A1(_212_),
    .A2(_188_),
    .B1(_193_),
    .B2(_186_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nor3_1 _363_ (
    .A(_134_),
    .B(_205_),
    .C(_210_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__a21oi_1 _364_ (
    .A1(_134_),
    .A2(_082_),
    .B1(_194_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nand3_1 _365_ (
    .A(_135_),
    .B(_206_),
    .C(_211_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__nand3_1 _366_ (
    .A(_205_),
    .B(_207_),
    .C(_152_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__nand2_1 _367_ (
    .A(_195_),
    .B(_196_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__a21o_1 _368_ (
    .A1(_203_),
    .A2(_150_),
    .B1(_206_),
    .X(_197_)
  );
  sky130_fd_sc_hd__o21ai_0 _369_ (
    .A1(_200_),
    .A2(_081_),
    .B1(_197_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__clkinv_1 _370_ (
    .A(_225_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__clkinv_1 _371_ (
    .A(_225_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__clkinv_1 _372_ (
    .A(_225_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__clkinv_1 _373_ (
    .A(_225_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__clkinv_1 _374_ (
    .A(_225_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__clkinv_1 _375_ (
    .A(_225_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__clkinv_1 _376_ (
    .A(_225_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__clkinv_1 _377_ (
    .A(_225_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__clkinv_1 _378_ (
    .A(_225_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__clkinv_1 _379_ (
    .A(_225_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__clkinv_1 _380_ (
    .A(_225_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__clkinv_1 _381_ (
    .A(_225_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__clkinv_1 _382_ (
    .A(_225_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__clkinv_1 _383_ (
    .A(_225_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__clkinv_1 _384_ (
    .A(_225_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__clkinv_1 _385_ (
    .A(_225_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__clkinv_1 _386_ (
    .A(_225_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__clkinv_1 _387_ (
    .A(_225_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__clkinv_1 _388_ (
    .A(_225_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__clkinv_1 _389_ (
    .A(_225_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__clkinv_1 _390_ (
    .A(_225_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__clkinv_1 _391_ (
    .A(_225_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__clkinv_1 _392_ (
    .A(_225_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__clkinv_1 _393_ (
    .A(_225_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__clkinv_1 _394_ (
    .A(_225_),
    .Y(_108_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfstp_2 _395_ (
    .CLK(clkin),
    .D(_255_),
    .Q(bit_idx[0]),
    .SET_B(_229_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfrtp_1 _396_ (
    .CLK(clkin),
    .D(_254_),
    .Q(bit_idx[1]),
    .RESET_B(_228_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfrtp_1 _397_ (
    .CLK(clkin),
    .D(_253_),
    .Q(bit_idx[2]),
    .RESET_B(_227_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfstp_2 _398_ (
    .CLK(clkin),
    .D(_266_),
    .Q(bit_idx[3]),
    .SET_B(_241_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfrtp_1 _399_ (
    .CLK(clkin),
    .D(_277_),
    .Q(cdac_sw[0]),
    .RESET_B(_252_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfrtp_1 _400_ (
    .CLK(clkin),
    .D(_276_),
    .Q(cdac_sw[1]),
    .RESET_B(_251_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfrtp_1 _401_ (
    .CLK(clkin),
    .D(_275_),
    .Q(cdac_sw[2]),
    .RESET_B(_250_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfrtp_1 _402_ (
    .CLK(clkin),
    .D(_273_),
    .Q(cdac_sw[3]),
    .RESET_B(_248_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfrtp_1 _403_ (
    .CLK(clkin),
    .D(_271_),
    .Q(cdac_sw[4]),
    .RESET_B(_246_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfrtp_1 _404_ (
    .CLK(clkin),
    .D(_269_),
    .Q(cdac_sw[5]),
    .RESET_B(_244_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfrtp_1 _405_ (
    .CLK(clkin),
    .D(_268_),
    .Q(cdac_sw[6]),
    .RESET_B(_243_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfrtp_1 _406_ (
    .CLK(clkin),
    .D(_267_),
    .Q(cdac_sw[7]),
    .RESET_B(_242_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfrtp_1 _407_ (
    .CLK(clkin),
    .D(_265_),
    .Q(cdac_sw[8]),
    .RESET_B(_240_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfrtp_1 _408_ (
    .CLK(clkin),
    .D(_270_),
    .Q(cdac_sw[9]),
    .RESET_B(_245_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfrtp_1 _409_ (
    .CLK(clkin),
    .D(_264_),
    .Q(result[0]),
    .RESET_B(_239_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfrtp_1 _410_ (
    .CLK(clkin),
    .D(_263_),
    .Q(result[1]),
    .RESET_B(_237_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfrtp_1 _411_ (
    .CLK(clkin),
    .D(_262_),
    .Q(result[2]),
    .RESET_B(_236_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfrtp_1 _412_ (
    .CLK(clkin),
    .D(_261_),
    .Q(result[3]),
    .RESET_B(_235_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfrtp_1 _413_ (
    .CLK(clkin),
    .D(_260_),
    .Q(result[4]),
    .RESET_B(_234_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfrtp_1 _414_ (
    .CLK(clkin),
    .D(_259_),
    .Q(result[5]),
    .RESET_B(_233_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfrtp_1 _415_ (
    .CLK(clkin),
    .D(_258_),
    .Q(result[6]),
    .RESET_B(_232_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfrtp_1 _416_ (
    .CLK(clkin),
    .D(_257_),
    .Q(result[7]),
    .RESET_B(_231_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfrtp_1 _417_ (
    .CLK(clkin),
    .D(_256_),
    .Q(result[8]),
    .RESET_B(_230_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfrtp_1 _418_ (
    .CLK(clkin),
    .D(_272_),
    .Q(result[9]),
    .RESET_B(_247_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfrtp_1 _419_ (
    .CLK(clkin),
    .D(_274_),
    .Q(done),
    .RESET_B(_249_)
  );
  (* src = "sar_logic_renamed.v:14.5-51.8" *)
  sky130_fd_sc_hd__dfrtp_1 _420_ (
    .CLK(clkin),
    .D(_002_),
    .Q(active),
    .RESET_B(_238_)
  );
  assign _138_ = cdac_sw[0];
  assign _277_ = _133_;
  assign _139_ = cdac_sw[1];
  assign _276_ = _132_;
  assign _140_ = cdac_sw[2];
  assign _275_ = _131_;
  assign _149_ = done;
  assign _274_ = _130_;
  assign _141_ = cdac_sw[3];
  assign _273_ = _129_;
  assign _224_ = result[9];
  assign _272_ = _128_;
  assign _142_ = cdac_sw[4];
  assign _271_ = _127_;
  assign _147_ = cdac_sw[9];
  assign _270_ = _126_;
  assign _143_ = cdac_sw[5];
  assign _269_ = _125_;
  assign _144_ = cdac_sw[6];
  assign _268_ = _124_;
  assign _145_ = cdac_sw[7];
  assign _267_ = _123_;
  assign _137_ = bit_idx[3];
  assign _002_ = _081_;
  assign _266_ = _122_;
  assign _146_ = cdac_sw[8];
  assign _265_ = _121_;
  assign _215_ = result[0];
  assign _264_ = _120_;
  assign _216_ = result[1];
  assign _263_ = _119_;
  assign _217_ = result[2];
  assign _262_ = _118_;
  assign _218_ = result[3];
  assign _261_ = _117_;
  assign _219_ = result[4];
  assign _260_ = _116_;
  assign _220_ = result[5];
  assign _259_ = _115_;
  assign _221_ = result[6];
  assign _258_ = _114_;
  assign _222_ = result[7];
  assign _257_ = _113_;
  assign _223_ = result[8];
  assign _256_ = _112_;
  assign _134_ = bit_idx[0];
  assign _255_ = _111_;
  assign _135_ = bit_idx[1];
  assign _254_ = _110_;
  assign _136_ = bit_idx[2];
  assign _253_ = _109_;
  assign _082_ = active;
  assign _226_ = start;
  assign _148_ = comp_in;
  assign _225_ = rst;
  assign _227_ = _083_;
  assign _228_ = _084_;
  assign _229_ = _085_;
  assign _230_ = _086_;
  assign _231_ = _087_;
  assign _232_ = _088_;
  assign _233_ = _089_;
  assign _234_ = _090_;
  assign _235_ = _091_;
  assign _236_ = _092_;
  assign _237_ = _093_;
  assign _238_ = _094_;
  assign _239_ = _095_;
  assign _240_ = _096_;
  assign _241_ = _097_;
  assign _242_ = _098_;
  assign _243_ = _099_;
  assign _244_ = _100_;
  assign _245_ = _101_;
  assign _246_ = _102_;
  assign _247_ = _103_;
  assign _248_ = _104_;
  assign _249_ = _105_;
  assign _250_ = _106_;
  assign _251_ = _107_;
  assign _252_ = _108_;
endmodule
